server:
  port: 7776

datasource:
  url: jdbc:mysql://10.253.116.46:3306/vie_biz?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: 123456

service:
  lifeins: http://localhost:7777
  sale: http://localhost:7772