server:
  port: 7508

datasource:
#  url: jdbc:mysql://101.37.72.72:5306/vie_biz_test?useUnicode=true&characterEncoding=UTF-8
#  username: iyb
#  password: Abcd2017
  url: jdbc:mysql://localhost:3307/biz?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: ftp123
