server:
  port: 7769

datasource:
  url: jdbc:mysql://101.37.72.72:5306/vie_biz_test?useUnicode=true&characterEncoding=UTF-8
  username: iyb
  password: Abcd2017

service:
  iyb: https://test.iyunbao.com
  dict: http://localhost:7773

