code: data

server:
  port: 7766

arcturus:
  biz:
    data: primary
    path: x:/arcturus/,x:/arcturus/,x:/arcturus/,x:/arcturus/
    files:
      children: 1
    index:
      cert: holder_cer_no,insurant_cer_no
      customer:
      user: owner_account
      mobile: mobile
      insure_date: insure_date
      policy_no: policy_no
  user:
    data: primary
    path: x:/arcturus/,x:/arcturus/,x:/arcturus/,x:/arcturus/
    index:
      parent_id: parent_id
      name: name
      mobile: mobile

datasource:
  url: jdbc:mysql://10.253.102.74:3306/rome
  username: iyb
  password: Abcd2017