env: dev

server:
  port: 7777

datasource:
  url: jdbc:mysql://10.253.116.46:3306/vie_biz
  username: admin
  password: Iyunbaotest2018

path:
  lifeins: ./product/

service:
  dict: http://localhost:7773