server:
  port: 7781

datasource:
  url: jdbc:mysql://101.37.72.72:5306/vie_biz_test?useUnicode=true&characterEncoding=UTF-8
  username: iyb
  password: Abcd2017

service:
  channel: http://localhost:7675
  product: http://localhost:7758
