server:
  port: 7781

datasource:
  url: jdbc:mysql://10.253.116.46:3306/vie_biz?useUnicode=true&characterEncoding=UTF-8
  username: admin
  password: Iyunbaotest2018

service:
  channel: http://localhost:7675
  product: http://localhost:7758
