server:
  port: 7570

datasource:
  url: jdbc:mysql://101.37.72.72:5306/vie_biz_test?useUnicode=true&characterEncoding=UTF-8
  username: iyb
  password: Abcd2017

service:
#  lifeins: http://localhost:7777
#  customer: http://localhost:7602
  dict: http://localhost:7773
#  order: http://localhost:7770
#  proposal: http://localhost:7776
#  user: http://localhost:7601
#  printer: http://localhost:7511
#  rome: http://localhost:7766
#  sale: http://localhost:7772
#  commission: http://localhost:7769
