server:
  port: 7570

datasource:
  url: jdbc:mysql://118.31.130.214:9001/vie_biz?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: 123456

service:
#  lifeins: http://localhost:7777
#  customer: http://localhost:7602
  dict: http://localhost:7773
#  order: http://localhost:7770
#  proposal: http://localhost:7776
#  user: http://localhost:7601
#  printer: http://localhost:7511
#  rome: http://localhost:7766
#  sale: http://localhost:7772
#  commission: http://localhost:7769
