env: dev

scope: iyb++,agency++,data++,user

server:
  port: 7666

management:
  context-path: /sys

endpoints:
  shutdown:
    enabled: true
    sensitive: false

datasource:
  url: jdbc:mysql://101.37.72.72:5306/athens_t?useUnicode=true&characterEncoding=UTF-8
  username: iyb
  password: Abcd2017
#  url: jdbc:mysql://www.lerrain.com:3307/athens?useUnicode=true&characterEncoding=UTF-8
#  username: root
#  password: ftp123

service:
  lifeins: http://localhost:7777
  proposal: http://localhost:7776
  customer: http://localhost:7602
  dict: http://localhost:7773
  order: http://localhost:7770
  user: http://localhost:7501
  printer: http://localhost:7511
  rome: http://localhost:7766
  sale: http://localhost:7772
  vienna: http://localhost:7701
  commission: http://localhost:7769
  fee: http://localhost:7768
  image: http://localhost:7771
  policy: http://localhost:7781
  channel: http://localhost:7675
  product: http://localhost:7758
  org: http://localhost:7731
  underwriting: http://localhost:7782

path:
  temp: x:/temp/1/

gatedir:

