env: dev

scope: iyb++,agency++,data++,user,clouds++

server:
  port: 7666

management:
  context-path: /sys

endpoints:
  shutdown:
    enabled: true
    sensitive: false

datasource:
  url: jdbc:mysql://10.253.116.46:3306/athens?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: 123456

service:
  lifeins: http://localhost:7777
  proposal: http://localhost:7776
  customer: http://localhost:7602
  dict: http://localhost:7773
  order: http://localhost:7570
  user: http://localhost:7501
  printer: http://localhost:7511
  rome: http://localhost:7766
  sale: http://localhost:7772
  vienna: http://localhost:7701
  commission: http://localhost:7769
  fee: http://localhost:7768
  image: http://localhost:7771
  policy: http://localhost:7781
  channel: http://localhost:7675
  product: http://localhost:7758
  org: http://localhost:7731
  underwriting: http://localhost:7782
  shop: http://localhost:7759
  template: http://localhost:7969
  varia: http://localhost:7508

path:
  temp: x:/temp/1/

gatedir:
