server:
  port: 7758

datasource:
  url: jdbc:mysql://10.253.116.46:3306/vie_biz?useUnicode=true&characterEncoding=UTF-8
  username: admin
  password: Iyunbaotest2018

service:
  iyb: https://test.iyunbao.com
  dict: http://localhost:7773

