env: dev

server:
  port: 7772

datasource:
  url: jdbc:mysql://118.31.130.214:9001/vie_biz?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: 123456

service:
  lifeins: http://localhost:7777
