server:
  port: 7772

datasource:
  url: jdbc:mysql://10.253.102.74:3306/vie_biz_test?useUnicode=true&characterEncoding=UTF-8
  username: iyb
  password: Abcd2017

service:
  boot: http://localhost:7500
  lifeins: http://localhost:7777
  customer: http://localhost:7602
  dict: http://localhost:7773
  order: http://localhost:7770
  proposal: http://localhost:7776
  sale: http://localhost:7772
  user: http://localhost:7601
  printer: http://localhost:7511
  vienna: http://localhost:7701
  iyb: http://test.iyunbao.com
  rome: http://localhost:7766

