env: dev

server:
  port: 7772

datasource:
  url: jdbc:mysql://101.37.72.72:5306/vie_biz_test?useUnicode=true&characterEncoding=UTF-8
  username: iyb
  password: Abcd2017
#  url: jdbc:mysql://www.lerrain.com:3307/vie_biz
#  username: root
#  password: ftp123

service:
  lifeins: http://localhost:7777
