env: dev

server:
  port: 7772

datasource:
  url: jdbc:mysql://10.253.116.46:3306/vie_biz?useUnicode=true&characterEncoding=UTF-8
  username: admin
  password: Iyunbaotest2018
#  url: jdbc:mysql://www.lerrain.com:3307/vie_biz
#  username: root
#  password: ftp123

service:
  lifeins: http://localhost:7777
